WANDB_PROJECT=qwen3-0.6B-product_key_expert_jumprelu-qproj \
		SAVE_DIR=checkpoints/product_key_expert_jumprelu_qproj \
		RUN_NAME=product_key_expert_jumprelu_q \
		MAX_TOKENS=100000000 \
		ARCHITECTURE=product_key_expert_jumprelu \
		K=32 \
		EXPANSION_FACTOR=1 \
		NUM_EXPERTS=1024 \
		ACTIVE_EXPERTS=2 \
		LATENTS_PER_EXPERT=56 \
		OPTIMIZER=adam \
		LR=8e-4 \
		HOOKPOINTS='layers.[3,14].self_attn.q_proj' \
		BATCH_SIZE=1 \
		GRAD_ACC_STEPS=8 \
		MICRO_ACC_STEPS=1 \
		AUXK_ALPHA=0.03125 \
		DEAD_FEATURE_THRESHOLD=10000000 \
		USE_HADAMARD=0 \
		COMPILE_MODEL=1 \
		bash scripts/autoresearch_test.sh

#####


WANDB_PROJECT=qwen3-0.6B-product_key_expert_jumprelu-qproj \
		SAVE_DIR=checkpoints/product_key_expert_jumprelu_qproj \
		RUN_NAME=product_key_expert_jumprelu_q \
		MAX_TOKENS=100000000 \
		ARCHITECTURE=product_key_expert_jumprelu \
		K=32 \
		EXPANSION_FACTOR=1 \
		NUM_EXPERTS=1024 \
		ACTIVE_EXPERTS=2 \
		LATENTS_PER_EXPERT=56 \
		OPTIMIZER=adam \
		LR=8e-4 \
		HOOKPOINTS='layers.[0-13].self_attn.q_proj' \
		BATCH_SIZE=1 \
		GRAD_ACC_STEPS=8 \
		MICRO_ACC_STEPS=1 \
		AUXK_ALPHA=0.03125 \
		DEAD_FEATURE_THRESHOLD=10000000 \
		USE_HADAMARD=0 \
		COMPILE_MODEL=1 \
		bash scripts/autoresearch_test.sh

WANDB_PROJECT=qwen3-0.6B-product_key_expert_jumprelu-qproj \
		SAVE_DIR=checkpoints/product_key_expert_jumprelu_qproj \
		RUN_NAME=product_key_expert_jumprelu_q \
		MAX_TOKENS=100000000 \
		ARCHITECTURE=product_key_expert_jumprelu \
		K=32 \
		EXPANSION_FACTOR=1 \
		NUM_EXPERTS=1024 \
		ACTIVE_EXPERTS=2 \
		LATENTS_PER_EXPERT=56 \
		OPTIMIZER=adam \
		LR=8e-4 \
		HOOKPOINTS='layers.[14-27].self_attn.q_proj' \
		BATCH_SIZE=1 \
		GRAD_ACC_STEPS=8 \
		MICRO_ACC_STEPS=1 \
		AUXK_ALPHA=0.03125 \
		DEAD_FEATURE_THRESHOLD=10000000 \
		USE_HADAMARD=0 \
		COMPILE_MODEL=1 \
		bash scripts/autoresearch_test.sh
